/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Lenovo
 */
public class DetailOrder extends javax.swing.JFrame {

    /**
     * Creates new form DetailOrder
     */
    public DetailOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTTDH = new javax.swing.JLabel();
        labelMaDH = new javax.swing.JLabel();
        labelTenNV = new javax.swing.JLabel();
        labelTenKH = new javax.swing.JLabel();
        labelDanhSachSP = new javax.swing.JLabel();
        labelNgayGiao = new javax.swing.JLabel();
        labelTongTien = new javax.swing.JLabel();
        valueMaDH = new javax.swing.JLabel();
        valueTenNV = new javax.swing.JLabel();
        valueTenKH = new javax.swing.JLabel();
        valueDSSP = new javax.swing.JLabel();
        valueNgayGiao = new javax.swing.JLabel();
        valueTongTien = new javax.swing.JLabel();
        labelNgayDat = new javax.swing.JLabel();
        valueNgayDat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelTTDH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTTDH.setText("Thông tin đơn hàng");

        labelMaDH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMaDH.setText("Mã đơn hàng: ");

        labelTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTenNV.setText("Tên nhân viên:");

        labelTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTenKH.setText("Tên khách hàng: ");

        labelDanhSachSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDanhSachSP.setText("Danh sách sản phẩm:");

        labelNgayGiao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNgayGiao.setText("Ngày giao:");

        labelTongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTongTien.setText("Tổng tiền: ");

        valueMaDH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueMaDH.setText("value_MDH");

        valueTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueTenNV.setText("value_TNV");

        valueTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueTenKH.setText("value_TKH");

        valueDSSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueDSSP.setText("value_DSSP");

        valueNgayGiao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueNgayGiao.setText("value_NgayGiao");

        valueTongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueTongTien.setText("value_TongTien");

        labelNgayDat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNgayDat.setText("Ngày đặt:");

        valueNgayDat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueNgayDat.setText("value_NgayDat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(labelTTDH))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTenNV)
                                .addGap(18, 18, 18)
                                .addComponent(valueTenNV))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelMaDH)
                                .addGap(18, 18, 18)
                                .addComponent(valueMaDH))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTenKH)
                                .addGap(18, 18, 18)
                                .addComponent(valueTenKH))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDanhSachSP)
                                .addGap(18, 18, 18)
                                .addComponent(valueDSSP))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTongTien)
                                .addGap(18, 18, 18)
                                .addComponent(valueTongTien))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelNgayGiao)
                                    .addGap(18, 18, 18)
                                    .addComponent(valueNgayGiao))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelNgayDat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valueNgayDat))))))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelTTDH)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaDH)
                    .addComponent(valueMaDH))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTenKH)
                    .addComponent(valueTenKH))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTenNV)
                    .addComponent(valueTenNV))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDanhSachSP)
                    .addComponent(valueDSSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNgayDat)
                    .addComponent(valueNgayDat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNgayGiao)
                    .addComponent(valueNgayGiao))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTongTien)
                    .addComponent(valueTongTien))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDanhSachSP;
    private javax.swing.JLabel labelMaDH;
    private javax.swing.JLabel labelNgayDat;
    private javax.swing.JLabel labelNgayGiao;
    private javax.swing.JLabel labelTTDH;
    private javax.swing.JLabel labelTenKH;
    private javax.swing.JLabel labelTenNV;
    private javax.swing.JLabel labelTongTien;
    private javax.swing.JLabel valueDSSP;
    private javax.swing.JLabel valueMaDH;
    private javax.swing.JLabel valueNgayDat;
    private javax.swing.JLabel valueNgayGiao;
    private javax.swing.JLabel valueTenKH;
    private javax.swing.JLabel valueTenNV;
    private javax.swing.JLabel valueTongTien;
    // End of variables declaration//GEN-END:variables
}
