/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Lenovo
 */
public class DetailBill extends javax.swing.JFrame {

    /**
     * Creates new form DetailBill
     */
    public DetailBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCTHD = new javax.swing.JLabel();
        labelMaHD = new javax.swing.JLabel();
        labelTenNV = new javax.swing.JLabel();
        labelTenKH = new javax.swing.JLabel();
        labelDSSP = new javax.swing.JLabel();
        labelNgayLHD = new javax.swing.JLabel();
        labelTongTien = new javax.swing.JLabel();
        valueMaHD = new javax.swing.JLabel();
        valueTenNV = new javax.swing.JLabel();
        valueTenKH = new javax.swing.JLabel();
        valueDSSP = new javax.swing.JLabel();
        valueNgayLHD = new javax.swing.JLabel();
        valueTongTien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCTHD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCTHD.setText("CHI TIẾT HÓA ĐƠN");

        labelMaHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMaHD.setText("Mã Hóa đơn: ");

        labelTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTenNV.setText("Tên nhân viên:");

        labelTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTenKH.setText("Tên khách hàng: ");

        labelDSSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDSSP.setText("Danh sách sản phẩm:");

        labelNgayLHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNgayLHD.setText("Ngày lập hóa đơn:");

        labelTongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTongTien.setText("Tổng tiền: ");

        valueMaHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueMaHD.setText("value_MHD");

        valueTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueTenNV.setText("value_TNV");

        valueTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueTenKH.setText("value_TKH");

        valueDSSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueDSSP.setText("value_DSSP");

        valueNgayLHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueNgayLHD.setText("value_NgayLHD");

        valueTongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueTongTien.setText("value_TongTien");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(labelCTHD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTenNV)
                                .addGap(18, 18, 18)
                                .addComponent(valueTenNV))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelMaHD)
                                .addGap(18, 18, 18)
                                .addComponent(valueMaHD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTenKH)
                                .addGap(18, 18, 18)
                                .addComponent(valueTenKH))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDSSP)
                                .addGap(18, 18, 18)
                                .addComponent(valueDSSP))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNgayLHD)
                                .addGap(18, 18, 18)
                                .addComponent(valueNgayLHD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTongTien)
                                .addGap(18, 18, 18)
                                .addComponent(valueTongTien)))))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelCTHD)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaHD)
                    .addComponent(valueMaHD))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTenKH)
                    .addComponent(valueTenKH))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTenNV)
                    .addComponent(valueTenNV))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDSSP)
                    .addComponent(valueDSSP))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNgayLHD)
                    .addComponent(valueNgayLHD))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTongTien)
                    .addComponent(valueTongTien))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCTHD;
    private javax.swing.JLabel labelDSSP;
    private javax.swing.JLabel labelMaHD;
    private javax.swing.JLabel labelNgayLHD;
    private javax.swing.JLabel labelTenKH;
    private javax.swing.JLabel labelTenNV;
    private javax.swing.JLabel labelTongTien;
    private javax.swing.JLabel valueDSSP;
    private javax.swing.JLabel valueMaHD;
    private javax.swing.JLabel valueNgayLHD;
    private javax.swing.JLabel valueTenKH;
    private javax.swing.JLabel valueTenNV;
    private javax.swing.JLabel valueTongTien;
    // End of variables declaration//GEN-END:variables
}
